all:

  facebook:
    api_key: 82ee875f32fb2c57541419dc238374a8
    api_secret: 7349c6082507cd0d13bb1784f75d883e
    api_id: 101447609894919
    redirect_after_connect: false
    redirect_after_connect_url: ''
    connect_signin_url: 'sfFacebookConnectAuth/signin'
    app_url: '/cre8'
    guard_adapter: ~
    js_framework: prototype # none, jQuery or prototype.

    # It is highly recommended to use a js framework if you want a correct experience in IE

  sf_guard_plugin:
    profile_class: sfGuardUserProfile
    profile_field_name: user_id
    profile_facebook_uid_name: facebook_uid # WARNING this column must be of type bigint ! 100000398093902 is a valid uid for example !
    profile_email_name: email
    profile_email_hash_name: email_hash

  facebook_connect:
    load_routing:     true
    user_permissions: [user]

  sf_guard_plugin:
    signin_form:          LoginForm
#    success_signin_url:   homepage
#    success_signout_url:  loggedOut
    remember_key_expiration_age: 2592000   # 30 days in seconds
    remember_cookie_name:        ccms

  sf_google_analytics_plugin:
    enabled:      false
    profile_id:   UA-8722664-1
    tracker:      google

  cre8_flash_slider2:
    width:                618
    height:               352
    buttonPos:            'top-left'
    showNav:              'true'
    showNumber:           'true'
    btnNumberBgColor:     '0xFFFFFF'
    bntNumberForeColor:   '0x000000'
    showArrow:            'true'
    btnArrowBgColor:      '0xFFFFFF'
    bntArrowForeColor:    '0x000000'
    showPause:            'true'
    btnPauseBgColor:      '0x999999'
    bntPauseForeColor:    '0xFFFFFF'
    btnSpace:             2


prod:

  sf_google_analytics_plugin:
    enabled:      true

  