<?php


/**
 * Skeleton subclass for performing query and update operations on the 'phpbb_topics_watch' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.0-dev on:
 *
 * czw, 4 mar 2010, 14:58:13
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.cre8PhpBBPlugin.lib.model
 */
class PhpbbTopicsWatchPeer extends BasePhpbbTopicsWatchPeer {

} // PhpbbTopicsWatchPeer
